import Head from 'next/head';
import { Layout } from '../../layout/Layout';
import { Button, Htag, P, Tag, Rating } from 'components';
import { useState } from 'react';

export default function Home(): JSX.Element {
	const [rating, setRating] = useState<number>(5);
	return (
		<Layout>
			<Head>
				<title>Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Htag tag='h1'>text</Htag>

			<Button appearance='primary' arrow='down'>
				text
			</Button>
			<Button appearance='ghost' arrow='down'>
				text
			</Button>
			<P fz='s'>asdasasdasd</P>
			<P fz='m'>asdasasdasd</P>
			<P fz='l'>asdasasdasd</P>
			<Rating rating={rating} setRating={setRating} isEditable />
		</Layout>
	);
}
