import { GetStaticProps } from 'next';
import Head from 'next/head';
import { withLayout } from '../../layout/Layout';
// import { useState } from 'react';
import axios from 'axios';
import { Layout } from '../../layout/Layout';
// import { Rating } from 'components';
import { MenuItem } from 'interfaces/menu.interface';

function Home({ menu }: HomeProps): JSX.Element {
	// const [rating, setRating] = useState<number>(5);
	return (
		<>
			<Head>
				<title>Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<ul>
				{menu.map((m, i) => (
					<li key={i}>{m._id.secondCategory}</li>
				))}
			</ul>
			{/* <Rating rating={rating} setRating={setRating} isEditable /> */}
		</>
	);
}
export default withLayout(Home);

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
	const firstCategory = 0;

	const { data: menu } = await axios.post<MenuItem[]>('https://courses-top.ru/api/top-page/find', {
		firstCategory,
	});

	return {
		props: {
			menu,
			firstCategory,
		},
	};
};

interface HomeProps extends Record<string, unknown> {
	menu: MenuItem[];
	firstCategory: number;
}
